import {
  AchievementBadge,
  Exercise,
  HealthPlatformSync,
  WorkoutLog,
  WorkoutRoutine,
} from '../types/workout';

export const INITIAL_EXERCISES: Exercise[] = [
  // Chest
  {
    id: 'ex-bench-press',
    name: 'Barbell Bench Press',
    category: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipment: 'Barbell',
    defaultRestSeconds: 120,
    notes: 'Keep shoulder blades retracted and feet planted firmly on floor.',
  },
  {
    id: 'ex-incline-db-press',
    name: 'Incline Dumbbell Press',
    category: 'Chest',
    secondaryMuscles: ['Shoulders', 'Triceps'],
    equipment: 'Dumbbell',
    defaultRestSeconds: 90,
    notes: '30-degree incline to target upper clavicular head.',
  },
  {
    id: 'ex-cable-crossover',
    name: 'Cable Chest Flyes',
    category: 'Chest',
    secondaryMuscles: ['Shoulders'],
    equipment: 'Cable',
    defaultRestSeconds: 60,
    notes: 'Focus on full squeeze at peak contraction without hyperextending shoulders.',
  },
  {
    id: 'ex-dips',
    name: 'Chest Dips',
    category: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipment: 'Bodyweight',
    defaultRestSeconds: 90,
    notes: 'Slight forward lean to bias lower pectorals.',
  },

  // Back
  {
    id: 'ex-deadlift',
    name: 'Conventional Barbell Deadlift',
    category: 'Back',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    equipment: 'Barbell',
    defaultRestSeconds: 180,
    notes: 'Pull slack out of the bar, brace core, drive through the mid-foot.',
  },
  {
    id: 'ex-pullup',
    name: 'Weighted Pull-Ups',
    category: 'Back',
    secondaryMuscles: ['Biceps', 'Core'],
    equipment: 'Bodyweight',
    defaultRestSeconds: 90,
    notes: 'Full dead hang to chin fully cleared over bar.',
  },
  {
    id: 'ex-barbell-row',
    name: 'Barbell Bent-Over Row',
    category: 'Back',
    secondaryMuscles: ['Biceps', 'Shoulders'],
    equipment: 'Barbell',
    defaultRestSeconds: 90,
    notes: 'Torso at 45 degrees, pull barbell towards belly button.',
  },
  {
    id: 'ex-lat-pulldown',
    name: 'Lat Pulldown (Neutral Grip)',
    category: 'Back',
    secondaryMuscles: ['Biceps'],
    equipment: 'Cable',
    defaultRestSeconds: 75,
    notes: 'Drive elbows down and back into your hips.',
  },

  // Legs (Quads, Hamstrings, Glutes, Calves)
  {
    id: 'ex-squat',
    name: 'Barbell Back Squat',
    category: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    equipment: 'Barbell',
    defaultRestSeconds: 180,
    notes: 'Hit parallel or below, knees tracking over toes with strong brace.',
  },
  {
    id: 'ex-romanian-deadlift',
    name: 'Romanian Deadlift (RDL)',
    category: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Back'],
    equipment: 'Barbell',
    defaultRestSeconds: 120,
    notes: 'Hinge hips backwards until deep hamstring stretch is felt, keep spine neutral.',
  },
  {
    id: 'ex-leg-press',
    name: 'Leg Press 45°',
    category: 'Quads',
    secondaryMuscles: ['Glutes', 'Calves'],
    equipment: 'Machine',
    defaultRestSeconds: 90,
    notes: 'Controlled descent, do not lock out knees aggressively at top.',
  },
  {
    id: 'ex-standing-calf-raise',
    name: 'Standing Calf Raise',
    category: 'Calves',
    secondaryMuscles: [],
    equipment: 'Machine',
    defaultRestSeconds: 60,
    notes: 'Hold deep stretch 2 seconds at the bottom of every rep.',
  },

  // Shoulders
  {
    id: 'ex-overhead-press',
    name: 'Overhead Barbell Press (OHP)',
    category: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Core'],
    equipment: 'Barbell',
    defaultRestSeconds: 120,
    notes: 'Tuck chin back on push, lock out directly over spine.',
  },
  {
    id: 'ex-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    category: 'Shoulders',
    secondaryMuscles: [],
    equipment: 'Dumbbell',
    defaultRestSeconds: 60,
    notes: 'Lead with elbows in the scapular plane, slight forward tilt.',
  },
  {
    id: 'ex-rear-delt-fly',
    name: 'Face Pulls (Rope Cable)',
    category: 'Shoulders',
    secondaryMuscles: ['Back'],
    equipment: 'Cable',
    defaultRestSeconds: 60,
    notes: 'External rotation at end range, pull thumbs toward ears.',
  },

  // Arms
  {
    id: 'ex-barbell-curl',
    name: 'Barbell Biceps Curl',
    category: 'Biceps',
    secondaryMuscles: [],
    equipment: 'Barbell',
    defaultRestSeconds: 60,
    notes: 'Strict form with zero hip swinging.',
  },
  {
    id: 'ex-tricep-pushdown',
    name: 'Tricep Rope Pushdown',
    category: 'Triceps',
    secondaryMuscles: [],
    equipment: 'Cable',
    defaultRestSeconds: 60,
    notes: 'Flare rope outward at bottom for full tricep peak contraction.',
  },
  {
    id: 'ex-skull-crusher',
    name: 'EZ-Bar Skull Crusher',
    category: 'Triceps',
    secondaryMuscles: [],
    equipment: 'Barbell',
    defaultRestSeconds: 75,
    notes: 'Lower bar behind forehead for greater long-head stretch.',
  },

  // Core & Calisthenics
  {
    id: 'ex-hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'Core',
    secondaryMuscles: [],
    equipment: 'Bodyweight',
    defaultRestSeconds: 60,
    notes: 'Curl pelvis up at top, avoid swinging momentum.',
  },
  {
    id: 'ex-cable-crunch',
    name: 'Kneeling Cable Crunch',
    category: 'Core',
    secondaryMuscles: [],
    equipment: 'Cable',
    defaultRestSeconds: 60,
    notes: 'Flex spine and pull elbows down into knees.',
  },
];

export const INITIAL_ROUTINES: WorkoutRoutine[] = [];

export const INITIAL_WORKOUT_LOGS: WorkoutLog[] = [];

export const INITIAL_HEALTH_PLATFORMS: HealthPlatformSync[] = [
  {
    platform: 'strava',
    name: 'Strava',
    icon: 'Zap',
    kind: 'oauth',
    enabled: false,
    status: 'idle',
    syncedWorkoutsCount: 0,
    autoExport: false,
    supportedMetrics: ['Workout upload (TCX)', 'Recent activity feed'],
    setupHint: 'Real integration: connect with OAuth, then upload finished workouts to Strava as strength activities.',
  },
  {
    platform: 'whoop',
    name: 'Whoop',
    icon: 'Activity',
    kind: 'unavailable',
    enabled: false,
    status: 'idle',
    syncedWorkoutsCount: 0,
    autoExport: false,
    supportedMetrics: [],
    setupHint: "Whoop's API blocks browser-based apps, so it can't connect from this web app. It needs a small server component.",
  },
  {
    platform: 'garmin',
    name: 'Garmin Connect',
    icon: 'Compass',
    kind: 'unavailable',
    enabled: false,
    status: 'idle',
    syncedWorkoutsCount: 0,
    autoExport: false,
    supportedMetrics: [],
    setupHint: 'Garmin requires approval into their developer program plus a server for webhooks — not available in this web app.',
  },
  {
    platform: 'samsung_health',
    name: 'Samsung Health',
    icon: 'Watch',
    kind: 'native_only',
    enabled: false,
    status: 'idle',
    syncedWorkoutsCount: 0,
    autoExport: false,
    supportedMetrics: ['Manual file import (TCX/CSV)'],
    setupHint: 'Samsung Health has no web API — it only syncs with native Android apps. Export a TCX file below and import it manually.',
  },
  {
    platform: 'apple_health',
    name: 'Apple Health',
    icon: 'Heart',
    enabled: false,
    kind: 'native_only',
    status: 'idle',
    syncedWorkoutsCount: 0,
    autoExport: false,
    supportedMetrics: ['Manual file import (XML/CSV)'],
    setupHint: 'Apple HealthKit is iOS-only with no web API. Export a file below and import it on your iPhone.',
  },
  {
    platform: 'health_connect',
    name: 'Google Health Connect',
    icon: 'Activity',
    kind: 'native_only',
    enabled: false,
    status: 'idle',
    syncedWorkoutsCount: 0,
    autoExport: false,
    supportedMetrics: ['Manual file import (TCX/CSV)'],
    setupHint: 'Health Connect is Android-only with no web API. Export a file below and import it on your phone.',
  },
];

export const INITIAL_ACHIEVEMENTS: AchievementBadge[] = [];

